export const RecommendedUsers = [
  { id: 1, name: "John Doe", username: "john doe" },
  { id: 2, name: "John Doe1", username: "john doe1" },
  { id: 3, name: "John Doe2", username: "john doe2" },
  { id: 4, name: "John Doe3", username: "john doe3" },
  { id: 5, name: "John Doe4", username: "john doe4" },
  { id: 6, name: "John Doe5", username: "john doe5" },
  { id: 7, name: "John Doe6", username: "john doe6" },
  { id: 8, name: "John Doe7", username: "john doe7" },
  { id: 9, name: "John Doe8", username: "john doe8" },
  { id: 10, name: "John Doe9", username: "john doe9" },
  { id: 11, name: "John Doe10", username: "john doe10" },
  { id: 12, name: "John Doe11", username: "john doe11" },
  { id: 13, name: "John Doe12", username: "john doe12" },
  { id: 14, name: "John Doe13", username: "john doe13" },
  { id: 15, name: "John Doe14", username: "john doe14" },
];