export const EmptyUser = {
  id: "",
  name: "",
  email: "",
  mobile: "",
  location: "",
  username: "",
  bio: "Hi! I’m on MEU, where are you?",
  avatar: "",
  pronounns: "",
  interests: [],
  purpose: "",
  linkedin: {
    email: "",
    email_verified: false,
    name: "",
    picture: "",
  },
  twitter: {
    id: "",
    username: "",
    name: "",
  },
  telegram: "",
};
